pipeline {
  agent {
    docker {
      image 'ualjjcanada/maven-firefox'
      args '-v "$HOME/.m2":/root/.m2 -v "$PWD":/usr/src -w /usr/src'
    }
  }

  stages {
    stage('Git Checkout') {
      steps {
        // Get some code from a GitHub repository
        git 'https://github.com/markhobson/docker-maven-firefox.git'
      }
    }

    stage('Firefox Tests') {
      steps {
        // Run Maven on docker agent.
        sh '''
          mvn clean verify
        '''
      }
      post {
        // If Maven was able to run the tests, even if some of the test
        // failed, record the test results.
        success {
          junit '**/target/surefire-reports/TEST-*.xml'
        }
      }
    }
  }
}
